- hosts: all
  gather_facts: false
  tasks:

  - name: Make sure we have a wheel group
    group:
      name: wheel
      state: present
  
  - name: Disable requiretty for synchro
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^Defaults:synchro'
      line: 'Defaults:synchro        !requiretty'
      validate: 'visudo -cf %s'

  - name: Allow synchro to run passwd passwordless
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^synchro'
      line: 'synchro ALL = NOPASSWD:ALL'
      validate: 'visudo -cf %s'

  - name: Add synchro user to wheel group
    user:
      name=synchro
      groups=wheel
      append=yes
      state=present
      createhome=yes
  
  - name: Set up authorized keys for the deployer user
    authorized_key: user=synchro key="{{item}}"
    with_file:
      - ~/.ssh/id_rsa.pub
