---
- hosts: all
  become: yes
  vars:
    mypassword: ansible
  tasks:
    - name: Change user password
      user:
        name: synchro
        update_password: always
        password: "{{ mypassword |password_hash('sha512') }}"
